### PR TITLE
New invite request - UI Iteration 1

### PR DESCRIPTION
**Pull request by rupalg**
In the spirit of having smaller PRs and getting help quickly, I have created this PR.

This PR does the following:
- It shows "New Invites" that come for the user.
- Currently, the profile cards, date, time, and the new invite message is hardcoded. 

I need help with:
- Figuring out a way to remove "Invites + Recieved + Sent" appBar from the top of the page. I have played around with the code, but it isn't clear to me yet how I can remove this appBar.
Screenshot 2023-07-27 at 8 53 13 PM

Next steps for this item would be to:
- Use non-hardcoded profile cards, date, time, and the new invite message

### CODE REVIEW

**Review by LucasMagnum — APPROVED** [review]

**Review by m-rosario — APPROVED** [review]
Thanks Rupal this looks great!

I added a commit to resolve your issue with the AppBar. Basically I am using the RouteAware methods to modify the main Scaffold whenever a push/pop occurs on the page. The ScaffoldModel takes care of setting the AppBar and notifying the Widget tree so that it can rebuild itself after the change.

Please take a look, and let me know if there is anything else you need help with!

**Review by ashlilili — APPROVED** [review]
Looks great Rupal!
Thanks Miguel for taking care of the extra app bar

**Comment by ashlilili** [comment]
> Thanks Rupal this looks great!
> 
> I added a commit to resolve your issue with the AppBar. Basically I am using the RouteAware methods to modify the main Scaffold whenever a push/pop occurs on the page. The ScaffoldModel takes care of setting the AppBar and notifying the Widget tree so that it can rebuild itself after the change.
> 
> Please take a look, and let me know if there is anything else you need help with!

Ooops you beat me to it XD

**Comment by rupalg** [comment]
Thank you Ashley for approving the PR, and Miguel for handling the extra app bar on the top. I have studied the code Miguel, and I will get some practice implementing routeaware methods in the future iterations

**Pull request merged**
